import { Locale, SiteContent } from "@/types/site";

export const locales: Locale[] = ["es", "pt", "en"];

export const siteContent: Record<Locale, SiteContent> = {
  es: {
    localeName: "Español",
    meta: {
      title: "Mensa Glam 2026 | Buenos Aires",
      description:
        "Encuentro social de Mensa LATAM en Buenos Aires del 27 al 29 de noviembre de 2026.",
    },
    nav: {
      brand: "Mensa Glam",
      languageLabel: "Idioma",
      placesPreviewLabel: "Lugares BA",
      sections: [
        { id: "overview", label: "Inicio" },
        { id: "schedule", label: "Agenda" },
        { id: "speakers", label: "Disertantes" },
        { id: "venue", label: "Lugar" },
        { id: "hotels", label: "Hoteles" },
        { id: "thanks", label: "Gracias" },
      ],
    },
    hero: {
      eyebrow: "Evento regional de Mensa LATAM",
      title: "Mensa Glam 2026",
      subtitle:
        "Un encuentro social para compartir ideas, juegos, amistades y conversaciones memorables.",
      date: "27 al 29 de noviembre de 2026",
      city: "Buenos Aires, Argentina",
      registration: "Formulario de inscripción",
      hotel: "Web del hotel",
      comingSoon: "Próximamente",
    },
    schedule: {
      title: "Agenda de charlas",
      note: "Programa preliminar. Algunos horarios o disertantes pueden cambiar.",
      days: [
        {
          day: "Viernes",
          sessions: [
            { time: "09:00", speaker: "Santiago Magnin" },
            { time: "10:15", speaker: "Esteban Elías" },
            { time: "11:30", speaker: "Gonzalo Burgos" },
          ],
        },
        {
          day: "Sábado",
          sessions: [
            { time: "09:00", speaker: "Mensa Paraguay" },
            { time: "10:15", speaker: "Mathesis" },
            { time: "11:30", speaker: "Julio Cesar Filho" },
          ],
        },
      ],
    },
    speakers: {
      title: "Disertantes",
      subtitle: "Algunos perfiles ya confirmados y espacio para próximos anuncios.",
      pendingLabel: "Pendiente",
      items: [
        {
          name: "Santiago Magnin",
          description: "Bio pendiente. Confirmado para la agenda del viernes.",
          image: "/speakers/Santiago.png",
        },
        {
          name: "Esteban Elías",
          description: "Bio pendiente. Confirmado para la agenda del viernes.",
          image: "/speakers/Esteban.jpg",
        },
        {
          name: "Gonzalo Burgos",
          description: "Bio pendiente. Confirmado para la agenda del viernes.",
          image: "/speakers/Gonzalo.jpg",
        },
        {
          name: "Marina Couto",
          description: "Vice presidente de IVNC (International Volunteer Network Committee). Miembro de Mensa desde 2015, Marina está en la Comisión de Mensa Brasil desde hace 10 años, apoyando su crecimiento exponencial.",
          image: "/globe.svg",
        },
      ],
    },
    venue: {
      title: "Lugar del encuentro",
      subtitle: "Palacio Juncal, en CABA.",
      placeName: "Palacio Juncal",
      addressLabel: "Dirección",
      address: "Juncal 1411, Recoleta, Ciudad Autónoma de Buenos Aires",
      mapTitle: "Mapa de ubicación",
      transportTitle: "Cómo llegar en transporte local",
      transport: [
        {
          title: "Subte",
          detail: "Línea D, estación Callao; luego caminata corta hacia Recoleta.",
        },
        {
          title: "Colectivos",
          detail: "Líneas con paradas cercanas: 10, 17, 39, 59, 60, 67, 102.",
        },
        {
          title: "Taxi o apps",
          detail: "Zona con buen acceso y alta disponibilidad en todo horario.",
        },
      ],
    },
    hotels: {
      title: "Hoteles con descuento",
      subtitle: "Elegí entre 3 opciones. Dos de ellas requieren código de referencia.",
      chooseLabel: "Compará precio, ubicación y forma de contacto para elegir la mejor opción.",
      chooseButton: "Reservar",
      directBooking: "Reservar",
      starsLabel: "Categoría",
      locationLabel: "Ubicación",
      phoneLabel: "Teléfono",
      whatsappLabel: "WhatsApp",
      emailLabel: "E-mail",
      copyEmail: "Copiar",
      copiedEmail: "E-mail copiado",
      ratesLabel: "Valores con descuento",
      referenceNeededTitle: "Código de referencia requerido",
      referenceNeededDescription:
        "Este hotel aplica la tarifa de Mensa Glam solo con código. Te redirigimos en {seconds} {unit} en una nueva pestaña.",
      referenceCodeLabel: "Referencia",
      autoRedirectLabel: "Redirección automática",
      secondsLabel: "segundos",
      openNow: "Abrir ahora",
      cancel: "Cancelar",
      popupBlockedMessage: "Tu navegador bloqueó la nueva pestaña. Usá 'Abrir ahora' o habilitá pop-ups para este sitio.",
      hotels: [
        {
          name: "NH Buenos Aires City",
          stars: 5,
          image: "/nh-buenos-aires-city.jpg",
          address: "Bolívar 160, Ciudad Autónoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Bolivar+160+CABA",
          phone: "+54 11 4121-6464",
          email: "nhcity@nh-hotels.com",
          bookingUrl: "https://www.minor-hotels.com/es/eventsweb/glam--encuentro-latinoamericano-de-mensa-",
          ratesTitle: "Valores con descuento",
          rates: [{ label: "Tarifa", value: "USD 130 + IVA por persona por noche con desayuno buffet" }],
          notes: ["Reembolso de IVA para turistas extranjeros"],
        },
        {
          name: "Atlas Tower Hotel",
          stars: 3,
          image: "/atlas-hotel-tower.jpeg",
          address: "Av. Corrientes 1778, Ciudad Autónoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/Av.+Corrientes+1778",
          phone: "(011) 5217-9371 / 4371-9371",
          whatsapp: "https://wa.me/541137819356",
          email: "reservas@atlastower.com.ar",
          bookingUrl: "http://www.atlastower.com.ar",
          referenceCode: "GLAM2026",
          ratesTitle: "Valores con descuento",
          rates: [
            { label: "Habitación Single", value: "AR$ 110.000 por noche con desayuno" },
            { label: "Habitación Doble", value: "AR$ 120.000 por noche con desayuno" },
            { label: "Habitación Triple", value: "AR$ 180.000 por noche con desayuno" },
          ],
        },
        {
          name: "Hotel Alpino",
          stars: 3,
          image: "/hotel-alpino.avif",
          address: "Cabello 3318, Palermo, Ciudad Autónoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cabello+3318+Palermo+CABA",
          whatsapp: "https://wa.me/5491130705151",
          email: "reservas@hotelalpino.com.ar",
          website: "http://www.hotelalpino.com.ar/",
          bookingUrl: "http://www.hotelalpino.com.ar/",
          referenceCode: "GLAM2026",
          ratesTitle: "Valores con descuento",
          rates: [
            { label: "Habitación Doble", value: "AR$ 130.500 por noche con desayuno" },
            { label: "Habitación Triple", value: "AR$ 171.000 por noche con desayuno" },
          ],
        },
      ],
    },
    thanks: {
      title: "Agradecimientos",
      subtitle: "Próximamente sumaremos aquí logos de aliados y colaboradores.",
      logoAlt: "Logo de aliado",
    },
  },
  pt: {
    localeName: "Português",
    meta: {
      title: "Mensa Glam 2026 | Buenos Aires",
      description:
        "Encontro social da Mensa LATAM em Buenos Aires de 27 a 29 de novembro de 2026.",
    },
    nav: {
      brand: "Mensa Glam",
      languageLabel: "Idioma",
      placesPreviewLabel: "Lugares BA",
      sections: [
        { id: "overview", label: "Início" },
        { id: "schedule", label: "Agenda" },
        { id: "speakers", label: "Palestrantes" },
        { id: "venue", label: "Local" },
        { id: "hotels", label: "Hotéis" },
        { id: "thanks", label: "Agradecimentos" },
      ],
    },
    hero: {
      eyebrow: "Evento regional da Mensa LATAM",
      title: "Mensa Glam 2026",
      subtitle:
        "Um encontro social para compartilhar ideias, jogos, amizades e conversas memoráveis.",
      date: "27 a 29 de novembro de 2026",
      city: "Buenos Aires, Argentina",
      registration: "Formulário de inscrição",
      hotel: "Site do hotel",
      comingSoon: "Em breve",
    },
    schedule: {
      title: "Agenda de palestras",
      note: "Programa preliminar. Alguns horários ou palestrantes podem mudar.",
      days: [
        {
          day: "Sexta-feira",
          sessions: [
            { time: "09:00", speaker: "Santiago Magnin" },
            { time: "10:15", speaker: "Esteban Elías" },
            { time: "11:30", speaker: "Gonzalo Burgos" },
          ],
        },
        {
          day: "Sábado",
          sessions: [
            { time: "09:00", speaker: "Mensa Paraguai" },
            { time: "10:15", speaker: "Mathesis" },
            { time: "11:30", speaker: "Julio Cesar Filho" },
          ],
        },
      ],
    },
    speakers: {
      title: "Palestrantes",
      subtitle: "Alguns perfis confirmados e espaço para próximos anúncios.",
      pendingLabel: "Pendente",
      items: [
        {
          name: "Santiago Magnin",
          description: "Bio pendente. Confirmado para a agenda de sexta-feira.",
          image: "/globe.svg",
        },
        {
          name: "Esteban Elías",
          description: "Bio pendente. Confirmado para a agenda de sexta-feira.",
          image: "/globe.svg",
        },
        {
          name: "Gonzalo Burgos",
          description: "Bio pendente. Confirmado para a agenda de sexta-feira.",
          image: "/globe.svg",
        },
        {
          name: "Marina Couto",
          description: "Vice-presidente do IVNC (International Volunteer Network Committee). Membro da Mensa desde 2015, Marina integra a diretoria da Mensa Brasil há 10 anos, apoiando o crescimento exponencial da organização nesse período.",
          image: "/globe.svg",
        },
      ],
    },
    venue: {
      title: "Local do encontro",
      subtitle: "Palacio Juncal, em CABA.",
      placeName: "Palacio Juncal",
      addressLabel: "Endereço",
      address: "Juncal 1411, Recoleta, Cidade Autônoma de Buenos Aires",
      mapTitle: "Mapa de localização",
      transportTitle: "Como chegar com transporte local",
      transport: [
        {
          title: "Metrô",
          detail: "Linha D, estação Callao; depois uma curta caminhada até Recoleta.",
        },
        {
          title: "Ônibus",
          detail: "Linhas próximas: 10, 17, 39, 59, 60, 67, 102.",
        },
        {
          title: "Táxi ou apps",
          detail: "Área com bom acesso e alta disponibilidade em qualquer horário.",
        },
      ],
    },
    hotels: {
      title: "Hotéis com desconto",
      subtitle: "Escolha entre 3 opções. Duas exigem código de referência.",
      chooseLabel: "Compare preço, localização e contato para decidir melhor.",
      chooseButton: "Reservar",
      directBooking: "Reservar",
      starsLabel: "Categoria",
      locationLabel: "Localização",
      phoneLabel: "Telefone",
      whatsappLabel: "WhatsApp",
      emailLabel: "E-mail",
      copyEmail: "Copiar",
      copiedEmail: "E-mail copiado",
      ratesLabel: "Tarifas com desconto",
      referenceNeededTitle: "Código de referência obrigatório",
      referenceNeededDescription:
        "Este hotel aplica a tarifa Mensa Glam somente com código. Vamos redirecionar em {seconds} {unit} em uma nova aba.",
      referenceCodeLabel: "Referência",
      autoRedirectLabel: "Redirecionamento automático",
      secondsLabel: "segundos",
      openNow: "Abrir agora",
      cancel: "Cancelar",
      popupBlockedMessage: "Seu navegador bloqueou a nova aba. Use 'Abrir agora' ou habilite pop-ups para este site.",
      hotels: [
        {
          name: "NH Buenos Aires City",
          stars: 5,
          image: "/nh-buenos-aires-city.jpg",
          address: "Bolívar 160, Cidade Autônoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Bolivar+160+CABA",
          phone: "+54 11 4121-6464",
          email: "nhcity@nh-hotels.com",
          bookingUrl: "https://www.minor-hotels.com/es/eventsweb/glam--encuentro-latinoamericano-de-mensa-",
          ratesTitle: "Tarifas com desconto",
          rates: [{ label: "Tarifa", value: "USD 130 + IVA por pessoa por noite com café da manhã buffet" }],
          notes: ["Reembolso de IVA para turistas estrangeiros"],
        },
        {
          name: "Atlas Tower Hotel",
          stars: 3,
          image: "/atlas-hotel-tower.jpeg",
          address: "Av. Corrientes 1778, Cidade Autônoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/Av.+Corrientes+1778",
          phone: "(011) 5217-9371 / 4371-9371",
          whatsapp: "https://wa.me/541137819356",
          email: "reservas@atlastower.com.ar",
          bookingUrl: "http://www.atlastower.com.ar",
          referenceCode: "GLAM2026",
          ratesTitle: "Tarifas com desconto",
          rates: [
            { label: "Quarto Single", value: "AR$ 110.000 por noite com café da manhã" },
            { label: "Quarto Duplo", value: "AR$ 120.000 por noite com café da manhã" },
            { label: "Quarto Triplo", value: "AR$ 180.000 por noite com café da manhã" },
          ],
        },
        {
          name: "Hotel Alpino",
          stars: 3,
          image: "/hotel-alpino.avif",
          address: "Cabello 3318, Palermo, Cidade Autônoma de Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cabello+3318+Palermo+CABA",
          whatsapp: "https://wa.me/5491130705151",
          email: "reservas@hotelalpino.com.ar",
          website: "http://www.hotelalpino.com.ar/",
          bookingUrl: "http://www.hotelalpino.com.ar/",
          referenceCode: "GLAM2026",
          ratesTitle: "Tarifas com desconto",
          rates: [
            { label: "Quarto Duplo", value: "AR$ 130.500 por noite com café da manhã" },
            { label: "Quarto Triplo", value: "AR$ 171.000 por noite com café da manhã" },
          ],
        },
      ],
    },
    thanks: {
      title: "Agradecimentos",
      subtitle: "Em breve adicionaremos aqui logos de parceiros e colaboradores.",
      logoAlt: "Logo de parceiro",
    },
  },
  en: {
    localeName: "English",
    meta: {
      title: "Mensa Glam 2026 | Buenos Aires",
      description:
        "Mensa LATAM social gathering in Buenos Aires, November 27-29, 2026.",
    },
    nav: {
      brand: "Mensa Glam",
      languageLabel: "Language",
      placesPreviewLabel: "BA Places",
      sections: [
        { id: "overview", label: "Home" },
        { id: "schedule", label: "Schedule" },
        { id: "speakers", label: "Speakers" },
        { id: "venue", label: "Venue" },
        { id: "hotels", label: "Hotels" },
        { id: "thanks", label: "Thanks" },
      ],
    },
    hero: {
      eyebrow: "Mensa LATAM regional event",
      title: "Mensa Glam 2026",
      subtitle:
        "A social gathering to share ideas, games, friendships, and memorable conversations.",
      date: "November 27-29, 2026",
      city: "Buenos Aires, Argentina",
      registration: "Sign-up form",
      hotel: "Hotel website",
      comingSoon: "Coming soon",
    },
    schedule: {
      title: "Talk schedule",
      note: "Preliminary program. Some times or speakers may change.",
      days: [
        {
          day: "Friday",
          sessions: [
            { time: "09:00", speaker: "Santiago Magnin" },
            { time: "10:15", speaker: "Esteban Elías" },
            { time: "11:30", speaker: "Gonzalo Burgos" },
          ],
        },
        {
          day: "Saturday",
          sessions: [
            { time: "09:00", speaker: "Mensa Paraguay" },
            { time: "10:15", speaker: "Mathesis" },
            { time: "11:30", speaker: "Julio Cesar Filho" },
          ],
        },
      ],
    },
    speakers: {
      title: "Speakers",
      subtitle: "Some confirmed profiles and space reserved for upcoming announcements.",
      pendingLabel: "Pending",
      items: [
        {
          name: "Santiago Magnin",
          description: "Bio pending. Confirmed for Friday schedule.",
          image: "/globe.svg",
        },
        {
          name: "Esteban Elías",
          description: "Bio pending. Confirmed for Friday schedule.",
          image: "/globe.svg",
        },
        {
          name: "Gonzalo Burgos",
          description: "Bio pending. Confirmed for Friday schedule.",
          image: "/globe.svg",
        },
        {
          name: "Marina Couto",
          description: "Vice-chair of IVNC (International Volunteer Network Committee). Mensa member since 2015, Marina has been on the board of Mensa Brazil for the past 10 years, supporting the exponential growth in Mensa Brazil during that period.",
          image: "/globe.svg",
        },
      ],
    },
    venue: {
      title: "Meeting venue",
      subtitle: "Palacio Juncal, in CABA.",
      placeName: "Palacio Juncal",
      addressLabel: "Address",
      address: "Juncal 1411, Recoleta, Autonomous City of Buenos Aires",
      mapTitle: "Location map",
      transportTitle: "How to arrive using local transport",
      transport: [
        {
          title: "Subway",
          detail: "Line D, Callao station, then a short walk toward Recoleta.",
        },
        {
          title: "Bus",
          detail: "Nearby lines include 10, 17, 39, 59, 60, 67, and 102.",
        },
        {
          title: "Taxi or ride apps",
          detail: "The area has good access and high availability all day.",
        },
      ],
    },
    hotels: {
      title: "Hotels with discount",
      subtitle: "Choose between 3 options. Two require a reference code.",
      chooseLabel: "Compare price, location, and contact channel to pick the best fit.",
      chooseButton: "Book",
      directBooking: "Book",
      starsLabel: "Category",
      locationLabel: "Location",
      phoneLabel: "Phone",
      whatsappLabel: "WhatsApp",
      emailLabel: "E-mail",
      copyEmail: "Copy",
      copiedEmail: "E-mail copied",
      ratesLabel: "Discounted rates",
      referenceNeededTitle: "Reference code required",
      referenceNeededDescription:
        "This hotel applies the Mensa Glam rate only with a code. We will redirect you in {seconds} {unit} in a new tab.",
      referenceCodeLabel: "Reference",
      autoRedirectLabel: "Automatic redirect",
      secondsLabel: "seconds",
      openNow: "Open now",
      cancel: "Cancel",
      popupBlockedMessage: "Your browser blocked the new tab. Use 'Open now' or allow pop-ups for this site.",
      hotels: [
        {
          name: "NH Buenos Aires City",
          stars: 5,
          image: "/nh-buenos-aires-city.jpg",
          address: "Bolívar 160, Autonomous City of Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Bolivar+160+CABA",
          phone: "+54 11 4121-6464",
          email: "nhcity@nh-hotels.com",
          bookingUrl: "https://www.minor-hotels.com/es/eventsweb/glam--encuentro-latinoamericano-de-mensa-",
          ratesTitle: "Discounted rates",
          rates: [{ label: "Rate", value: "USD 130 + VAT per person per night with buffet breakfast" }],
          notes: ["VAT refund for foreign tourists"],
        },
        {
          name: "Atlas Tower Hotel",
          stars: 3,
          image: "/atlas-hotel-tower.jpeg",
          address: "Av. Corrientes 1778, Autonomous City of Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/Av.+Corrientes+1778",
          phone: "(011) 5217-9371 / 4371-9371",
          whatsapp: "https://wa.me/541137819356",
          email: "reservas@atlastower.com.ar",
          bookingUrl: "http://www.atlastower.com.ar",
          referenceCode: "GLAM2026",
          ratesTitle: "Discounted rates",
          rates: [
            { label: "Single room", value: "AR$ 110,000 per night with breakfast" },
            { label: "Double room", value: "AR$ 120,000 per night with breakfast" },
            { label: "Triple room", value: "AR$ 180,000 per night with breakfast" },
          ],
        },
        {
          name: "Hotel Alpino",
          stars: 3,
          image: "/hotel-alpino.avif",
          address: "Cabello 3318, Palermo, Autonomous City of Buenos Aires",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cabello+3318+Palermo+CABA",
          whatsapp: "https://wa.me/5491130705151",
          email: "reservas@hotelalpino.com.ar",
          website: "http://www.hotelalpino.com.ar/",
          bookingUrl: "http://www.hotelalpino.com.ar/",
          referenceCode: "GLAM2026",
          ratesTitle: "Discounted rates",
          rates: [
            { label: "Double room", value: "AR$ 130,500 per night with breakfast" },
            { label: "Triple room", value: "AR$ 171,000 per night with breakfast" },
          ],
        },
      ],
    },
    thanks: {
      title: "Thanks",
      subtitle: "Partner and supporter logos will be added here soon.",
      logoAlt: "Partner logo",
    },
  },
};
